[colors]
ansi = [
    "#e9e9ed",
    "#f52a65",
    "#587539",
    "#8c6c3e",
    "#2e7de9",
    "#9854f1",
    "#007197",
    "#6172b0",
]
background = "#e1e2e7"
brights = [
    "#a1a6c5",
    "#f52a65",
    "#587539",
    "#8c6c3e",
    "#2e7de9",
    "#9854f1",
    "#007197",
    "#3760bf",
]
cursor_bg = "#3760bf"
cursor_border = "#3760bf"
cursor_fg = "#e1e2e7"
foreground = "#3760bf"
selection_bg = "#b6bfe2"
selection_fg = "#3760bf"

[colors.indexed]

[colors.tab_bar]
background = "#191b28"
inactive_tab_edge = "#e9e9ec"

[colors.tab_bar.active_tab]
bg_color = "#e1e2e7"
fg_color = "#2e7de9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#e9e9ec"
fg_color = "#8990b3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#e9e9ec"
fg_color = "#2e7de9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#191b28"
fg_color = "#2e7de9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#2e7de9"
fg_color = "#e9e9ec"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "folke"
name = "Noctalia"
