[colors]
ansi = [
    "#002b36",
    "#dc322f",
    "#859900",
    "#b58900",
    "#268bd2",
    "#6c71c4",
    "#2aa198",
    "#93a1a1",
]
background = "#fdf6e3"
brights = [
    "#657b83",
    "#dc322f",
    "#859900",
    "#b58900",
    "#268bd2",
    "#6c71c4",
    "#2aa198",
    "#fdf6e3",
]
foreground = "#586e75"

[colors.indexed]

[metadata]
author = "Chris Kempson"
name = "Noctalia"

